# minio-secret.yaml (DO NOT COMMIT THIS)
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
stringData:
  rootUser: xxxxx
  rootPassword: yyyyyy