apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: observability-cluster
servers: 1
agents: 2
image: rancher/k3s:v1.29.6-k3s1 # Pin it, don't use latest

# Expose Kubernetes API on localhost:6443
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6443"

volumes:
  - volume: k3d-observability-data:/var/lib/rancher/k3s/storage@all

# Map HTTP and HTTPS for Ingress (Argo CD, sample apps, etc.)
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer


options:
  k3d:
    wait: true
    timeout: "300s" # was 120s - too low for Windows
  k3s:
    extraArgs:
#      - arg: --disable=traefik
       - arg: --disable=metrics-server
         nodeFilters:
           - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
