---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: monitoring
spec:
  encryptedData:
    rootPassword: AgAtJLcurRwibZo83iOwnkA/WDtbdsatb4AC+nQiUU6Nh5PD6WgsP2uGDOCTdzpHxmAnfPH6KzP+bJyn3H70XKmSi6QKeR6GItWTzswTKsrwW54nNTIUPIdtcEpOM0A73NSQVCMNxWkj2HIzsFSktOaft5Ip7nrReNC7wREbPHGOXo4rXK5P4cNvitt7GpxZR4ph8hfqKxWXnUSSFdv95tdfenTd3fCEgTXEBQsue0LWX0Ccd/aFwsu6Urh/tEcwiPz7tEVXs7hpMGaPk1r62ZsVzBJTZgBg2ouzxjc4GgwAW/kBm0dWuHISrYaAC2pmp7RTgQwF/1Brzdh3N3/tBzsuzy9YW3Woo5IBXe0Om0oFo6lu0CaaIT+QKgNITW5q2qlFW4TUvTl64ira/n5PLiYjpSoJD9QUkKOqwBAvaIwtZlXJlJ5fnz3x1ZeFQPudH4t7y+5hClo6xrWyNQDvCh1MFPeK/jNoh+4r0cIK3LL0ZVx/ZmA3j9h7Kw2nd7zuFdh6nCnnU8LDYS72DwJKXJzD8BG1rtaEUP286r0ot9PvP0QSMc3zK6M4uICQTS0S+EqajEYDRsJauz11K9dN+qacVpNqO26ErAJoxm9hPwF2RYgHlFqY+/oAEb+VnztoDwWvNHt3KZD+A+tM8CwEvln5TlJXD0KIyC+Spwh9T6Tx0N7vGxX98GJXkdASltchMLNJ8EHlvvRR+slK
    rootUser: AgA2lUpzlf6xb1FZBGZ2Alj0KEUWo1AUiKGXMbis+VQ8N3uTrEVqXJybDG9OzkuBY0I0MSzG2tfPJ6Op+n/9/5wDxblZY4Txn4Vmvl7qyqm8IRppHr4mXHwN0PBZLPwPUnroczb3DrQLHKW88BTPB4i6FIGJMB0n/ruqs8afRB//H9e/FvlW1wAEOXiNsMwr360PQtd7Zb60ywZ2hGL1pRNZw2/5ltBwfJG/esUBqlM7lEKg+8O9sK5sz0dCikMkcPiIkyWls7Zaq+Z4jvpKUrg8Wq4uwxKV5dFILmoZUIiYHvJpi/YBVeh6iEW6cunghVz29OhS4Olsuo6YuEvJLa5CHAhYa7IKhGZr6DMqGAKIjCG6AZVMabYPKO7Um8GjDe3k6tIbBKK2B1PvhZ7x9oN0WVSwA+4VR3QqQr4hHHr2WAx/KXLEu3FoRr5KSFpGFmD1aR8jmdOaTmjeHgXGPxaMumGazgT0ii4lcbESofez+ArrlAybYMfbvV688HFjfLfm24LZG/0T60CL+auFGTsPWWH62zSBTHRDV6pYg1nLcHH3J2Ze+57jOEoOPF2tKzeAx6rNnJpZvln1oRIzOJPNtc4cdZ9BFl52dJ8DcwNbySJo0ChYkWAGJRyu7x0Cz6Wk8T//2BCLENGH4Ol7Z/E3GBOlps+oo92nnmHUlWgQsSlvhI4KAdHHMVGXc0ruQjTvXp7Qop8=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      name: minio-credentials
      namespace: monitoring
