---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: monitoring
spec:
  encryptedData:
    rootPassword: AgDLbodhzOvlSy0HZhHQ82CtjWNn8fNzT7r+QhEiZIbc38v1O/8KaRGLCDBLfAyRncVFQJKxyDsp9UcSWc+w7e8IRWPxhHGVjR56fuZqTnszcnq27n7n9PEGB/xfgil2YKScnQkYcRYwHidqB1byzrC2P2Oe4t6R66tdQKhZ5xJKqjCSX13/jAmfv4+WXMCXQgVWVoaP+hTfqsn6aZfmn8rt+s7w0OPtbOQRZK2yVQOUsLQpuRdt8FjXjY94XbqT27Xwk5L0GjG3jRJUxOszcbH7XsoTiY1dwMG7kywhe3BQ17lAH66A5YcYNFpdoCf9jvBDXdXukjPhueQhICWpoJiBHEX6NzLoqH929izg0Rd60Eprw9mCOOAwO0KD+r5ngaB5nHloxAN/q8JqJufmTOIRQHDlpSoyb8fxUnOVmvFNIy44uyxorh32/8+KsDDtIxa1Ceg6pKVMyUwJlx5hSLwQX3vWYKAwFa+hX14RR7d8n6VLuH/IR+tOrodtvbJejee80GEDKlwPU0lqsmbaVc3fJgivb6qP0BQa1JOCunzV63ziIFtUFiSRb/Zu7O84XS43MategXjg9en5I4e8B+3FIASCBjkzp2ugAwbAjI07lEIfCN2qMCydfs4Fu4JNMkaV9I+VrYC0tbRyDvDRRRc18YzuTIYV2qLT8bkrFpt4qeFZLTUbfSmgRfJAAAuC+TvwLIUJ2A/5dk0k
    rootUser: AgCD/U8bRFMpleW88jvmmLpjSJMUG/6mOO1QZOo0gFuC/HDVfMuNAMWLlEh2pz22XOvKYpApvpmLLN+l4Hh1h7+g2NC0IHe4MOBvsty28gBCLh5oI7wKFBJ2gqxCw5wGDUAo7pzWb6dWi+Cae7JJltcaw/RmrbaCY+6oIfOtygTUO9shgPuEhQ+BYLNpKcPT0/1GpGj3ftoxlMXupjW4ILRtHgqrL5PPcXTC7qP6dXleOkiW0DvAED2WzOj9iWs6L70tNKFSDKbD//kI2+emBfq4Fdv/3el94LC8cVzX4CJirPB7hAlZuq4YjNjCVwZcCmOThRBM4OffMwMqgPSbz5JMlGHpZsrWgLXxpaXnnKzZ3AUH7b+/Ny1hOTWltXd7RlnmhLLko2pwnxYSrnoEs2Uw/I48A4cVYBh08cIbTRAhouNzUwFFkVJKk0TIMkpRWBxfrFc7TagYjbj4AeUzSDdqG+ZWGAoxAKfSE5h2JdsUjHurSlQqZ6paStbSsQRwrszfTREaPcg/hmEsr0GdOMJIRgDWFvPLYZx+mqwB4EXzlpAsYa25FDtDDGh58H+M0wEFAmddTJC2oIGt7RjFMpyOWkb9dD/Wrh5KI7lLLJswFdwXBCWtplOd3Z4G59biaH81ZgBinrYnQvJoZfGNMJdnzd1NC/ygv8vGSc0T+Oc5SEz2gxtNE51sNRzJwcGJouyiyL1rh4Q=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      name: minio-credentials
      namespace: monitoring
