---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: monitoring
spec:
  encryptedData:
    rootPassword: AgCTzKVuA+u+z2fjBc28WoHBSZEMC02U3O4W/bplTUo/wBHQPqnaDK9dWmHyUYx5jdcOosIroC15qbKrPUb6v6wLv8eieInisXvonIKZDAoNVonBxYgpt38sjIbVUbNz1iajIftpSKj2N5Mr7o8gbVMjiwfnNgzd2Mbna1rZ+/mWkfqwodEvMytlhex7kPttSpZosms+pHOYXNzH2EWzWs9MTHpgWKiA8hoI1ZbRlERKTF+aFhwPvDH2C0R68b6I20Z1Cgn7/5oXBTzdzMJ3ohZqRK06A6HwGBPSUgeKhtqzQLavMFVDHyQBuJoqTUNqCXdhlmLqcBw14nTxXO8p0hbGyx2TJ5PseRteRvdozxGdksSJ887toXNt2157J4TOa+MBFCA6NmeqSg1T68AncST8JOBdQzjn0GPR6A+eYs79WzpZj++YhXFMmz+4oZCFqLcwKxdHBb5SCUQE1yfYkVAKhabjwz0FacrAqcDkFbnlpW4QrzHnFThbkJtBGTWHzvkjDzrifqjVK15mL7dOWJQ5MJoEQZIHeApRN5qVm8BR8yX+XOJKF0gv54r3uKDC1+RK2HYM5zdTJ2BzxV3REwe4T+slvPA8sVFePeWJfN9z/KX0rGGzkmdr5k7D5h1odlfWKUuUufBMDE47emllGa7yg5cJkK5D9tsTXWIVSwRDpybaTKF9v0iZGIEKLeND1ecqtrChFQU77CoE
    rootUser: AgCptl4O/tYkeI4zxWWWZ8nOdqBsN+NBN0xbqprEYzC0Mp51/I07Te3fd0F5+BpFoICZUvA8oXap+k9MJK61YHkpN/KFQ19OIdIL6uJTbC5nb1brDqnjHvFBcRV+AkH4aBNdfZFolvXqLfgWpUwbiw1qLQfuBfpiTz0RlCgnx7tHBCktBi+5qxSGiloA104LHebLvETflWeYIrq2TU6+Gn4TOIBcMr4P8BLi7e5FBB9DsEDfKPBSqcWPz2GXNPLff3b1cDnyR9Fyj99aFfXYC7yqYyIdV/pFfuFtu/+iw6fGOD52djxLt3/ausZt8fUgJu2xRlokTwtL3Q0pfiG1ffun9XMx8rx7xaG5MBbag2HS1NMUs1CuA5loIPAHKGPscgC6gvpmV/DKsBpA9rQ/Tr4RwRB3UINHxfJ0G5vYS4ejnmC7fGsPF5AL90qXWzbFjlfrf9WBirVkLxGBpeiMEuw+utOGKhIJ+mCBZWsW1SDP1i8s5endVBaz0SXLFUUbIAKdi33MCPDmPl/WWles6ltfBu1lCUP2uWCFz55MobuOctcsfPqq2UMMs9EO0Mdgm74Uuq4sorNuThcJO5V3vecydLu4XQ0Q5YSAWRjAuxeRuEAgpgSIJJn6lupJhqjIYyoTBHENHm/fbcSJmzagleHgMErTLMSB7kTRhBNyVJdlj0UE6HyMqFHHyc9AlVcsKJilITWxPlY=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      name: minio-credentials
      namespace: monitoring
