apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    # Source 1: The remote Prometheus Helm chart repository
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 87.21.0
      helm:
        valueFiles:
        - $GitRepo/apps/monitoring/prometheus-grafana-values.yaml
    
    # Source 2: Your Git repository containing the custom values file
    - repoURL: https://github.com/swamyvaditya/k3d-observability-lab.git
      targetRevision: main
      ref: GitRepo
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true