---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack
  namespace: monitoring
spec:
  encryptedData:
    slack_api_url: AgCRJrR4/ArLo9nbfdnf0QVh9LnQI/YZwMP8Neag6G30BaJoQUng+Owm4P2RwAOAmTXMKdqFfXWVC+LKlik5CczenKgFs8PJEGgTOlVgJSzhAfWdsqCZFD6A70W/4C7lv2rNY+d6YFKOSg87LIqWYusiGLdsuObOET41xstsgOHOpjVMC+sZAsgrA4kaGEsCv10qBSvOHdQ+lTBt/mUHPmFSWSMSrSl9mpS3JnzcM8oZtg9beshhAhgMr+gr2L4Dq1G1muStQFbHEVZG0v9YD5iB5huhLWhngPq9zFJycyatEif2JQX6uFNzxRxdnKtGPGP9cVTvMFXeFstz8b2I0tAKSzvDqpkCEOdecDiTyz+gJ048pRtFl4VFODf00xJK5jtm+PDxAaIPT9AJ0/cUTteA4cG1w0BaBtPitH1uWIdTjU0qw9s1XJBv2cXBWb0pPv3J5knjU9WDfJDNqlffTbi13+OyN+ndJSbUzdjAf9fHcGtlMwCTDIfXWmFA6NtbED8ULKknYv323K9ZGh8KEyZCbIhBDJSArYC4QiPzCDEDzJvbqKk500SV53PowNv0lz/Vm1M0CKtmgOcfHn4VZXTGRYaGNeeqEVc4DjmcU8Oj/CR8cI4F50B7u7IxBRzBUXLIY+HmZj9cjxkmo7ZNsXbsVFdi5KMlbzQeoeZbE/MIXu74QalowSXcQCluOTKneCdQ4Qi6Vv2FcnaBOgFRmHU0A68EcnjgPs/eldYjmmlnbA/JhuQLiqe61IARLfZrn1NErLbkltPKXcywYX5Jept3yGXfuZETTG6XASAIdGIKROg=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      name: alertmanager-slack
      namespace: monitoring
