apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    # Source 1: The remote Grafana Tempo Helm chart repository
    - chart: tempo
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.10.0
      helm:
        valueFiles:
          - $GitRepo/apps/monitoring/tempo-values.yaml
    
    # Source 2: Your Git repository containing the custom values file
    - repoURL: https://github.com/swamyvaditya/k3d-observability-lab.git
      targetRevision: main
      ref: GitRepo

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true