{
 "title": "01 - Infra Cluster Overview",
 "tags": [
  "phase2",
  "sre",
  "golden-signals"
 ],
 "panels": [
  {
   "title": "Cluster CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m]))*100"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes)/sum(machine_memory_bytes)*100"
    }
   ]
  },
  {
   "title": "Node CPU - USE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by(node)(rate(container_cpu_usage_seconds_total[5m]))"
    }
   ]
  },
  {
   "title": "Node Memory - USE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by(node)(container_memory_working_set_bytes)"
    }
   ]
  }
 ]
}