{
 "title": "05 - Logs - Loki",
 "panels": [
  {
   "title": "All Service Logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=~\".+\"}"
    }
   ]
  },
  {
   "title": "Logs Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate({service_name=~\".+\"}[1m])"
    }
   ]
  },
  {
   "title": "Error Logs Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"otel-demo\"} |= \"ERROR\" [5m]))"
    }
   ]
  },
  {
   "title": "Cart Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=\"cart\"}"
    }
   ]
  },
  {
   "title": "Frontend Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=\"otel-demo\"} |= \"frontend\""
    }
   ]
  },
  {
   "title": "Checkout Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{service_name=\"otel-demo\"} |= \"checkout\""
    }
   ]
  }
 ]
}